install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive

branches:
  except:
  - develop

stages:
  - test
  - doc

jobs:
  include:
    - stage:  test
      script: l3build check -H --engine xetex  --shuffle --first aaa-loading || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )
      name:   "XeTeX tests"
    - script: l3build check -H --engine luatex --shuffle --first aaa-loading || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )
      name:   "LuaTeX tests"
    - stage:  doc
      script: l3build doc
      name:   "Typesetting documentation"
